token = "XXXXXXXXXXXXXXXXXXXX"  # str
dcteam_role_id = "XXXXXXXXXXXXXXXXX"  # int
dcteam_id = "XXXXXXXXXXXXXXXXXX"  # int
token_youtube = "XXXXXXXXXXXXXXXXXXX"  # str
DEVELOPER_CX = "XXXXXXXXXXXXXXXXXXXXXXXXXXX" # str